# Generated by Django 4.2.3 on 2023-07-22 00:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Conteudos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=225)),
                ('create_at', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='GrauAplicacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=225)),
                ('create_at', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Publico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=225)),
                ('create_at', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=225)),
                ('create_at', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Projetos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=225)),
                ('descricao', models.CharField(max_length=225)),
                ('url_imagem', models.CharField(max_length=225)),
                ('create_at', models.DateField(auto_now_add=True)),
                ('conteudo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='GdsSystem.conteudos')),
                ('grauAplicacao', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='GdsSystem.grauaplicacao')),
                ('publico', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='GdsSystem.publico')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GdsSystem.usuario')),
            ],
        ),
    ]
