# Generated by Django 4.2.3 on 2023-08-03 00:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GdsSystem', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projetos',
            name='estilo_aprendizagem',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='GdsSystem.estiloaprendizagem'),
        ),
        migrations.AddField(
            model_name='projetos',
            name='habilidades',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='GdsSystem.habilidades'),
        ),
        migrations.AddField(
            model_name='projetos',
            name='interesses',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='GdsSystem.interesses'),
        ),
        migrations.AlterField(
            model_name='projetos',
            name='conteudo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='GdsSystem.conteudos'),
        ),
        migrations.AlterField(
            model_name='projetos',
            name='create_at',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='projetos',
            name='disciplinas',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='GdsSystem.disciplinas'),
        ),
        migrations.AlterField(
            model_name='projetos',
            name='grauAplicacao',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='GdsSystem.grauaplicacao'),
        ),
        migrations.AlterField(
            model_name='projetos',
            name='publico',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='GdsSystem.publico'),
        ),
        migrations.AlterField(
            model_name='projetos',
            name='series',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='GdsSystem.series'),
        ),
        migrations.AlterField(
            model_name='projetos',
            name='usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='GdsSystem.usuario'),
        ),
    ]
