# Generated by Django 4.2.3 on 2023-07-22 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GdsSystem', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projetos',
            name='url_imagem',
            field=models.CharField(max_length=225, null=True),
        ),
    ]
