# Generated by Django 4.2.3 on 2023-08-05 01:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GdsSystem', '0002_projetos_estilo_aprendizagem_projetos_habilidades_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projetos',
            name='competicaoDesafios',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='GdsSystem.competicoesdesafios'),
        ),
        migrations.AddField(
            model_name='projetos',
            name='recompensasVirtuais',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='GdsSystem.recompensasvirtuais'),
        ),
    ]
