# Generated by Django 4.2.3 on 2023-07-22 01:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GdsSystem', '0002_alter_projetos_url_imagem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projetos',
            name='conteudo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GdsSystem.conteudos'),
        ),
        migrations.AlterField(
            model_name='projetos',
            name='grauAplicacao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GdsSystem.grauaplicacao'),
        ),
        migrations.AlterField(
            model_name='projetos',
            name='publico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GdsSystem.publico'),
        ),
    ]
