# Generated by Django 4.2.3 on 2023-08-05 01:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GdsSystem', '0003_projetos_competicaodesafios_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projetos',
            name='configuracaoespaco',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='GdsSystem.configuracaoespaco'),
        ),
        migrations.AddField(
            model_name='projetos',
            name='disponibilidadeTec',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='GdsSystem.disponibilidadetec'),
        ),
        migrations.AddField(
            model_name='projetos',
            name='normasRegras',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='GdsSystem.normasregras'),
        ),
        migrations.AddField(
            model_name='projetos',
            name='professorAluo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='GdsSystem.professoraluno'),
        ),
        migrations.AddField(
            model_name='projetos',
            name='recursos',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='GdsSystem.recursos'),
        ),
    ]
