# Generated by Django 4.2.3 on 2023-07-26 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GdsSystem', '0003_alter_projetos_conteudo_alter_projetos_grauaplicacao_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AoRedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selectedInterests', models.CharField(max_length=100)),
                ('selectedSkills', models.CharField(max_length=100)),
                ('selectedPersonality', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ConteudoAplicado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selectedGrau', models.CharField(max_length=100)),
                ('selectedSerie', models.CharField(max_length=100)),
                ('selectedDisciplina', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Gostam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selectedRecursos', models.CharField(max_length=100)),
                ('selectedConfiguracaoEspaco', models.CharField(max_length=100)),
                ('selectedRelacaoProfessorAluno', models.CharField(max_length=100)),
                ('selectedDisponibilidadeTecnologia', models.CharField(max_length=100)),
                ('selectedNormasRegras', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Jogadores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selectedAgeRange', models.CharField(max_length=100)),
                ('selectedExperience', models.CharField(max_length=100)),
                ('selectedObjectives', models.CharField(max_length=100)),
                ('selectedMotivation', models.CharField(max_length=100)),
                ('selectedLearningStyle', models.CharField(max_length=100)),
                ('selectedSpecialNeeds', models.CharField(max_length=100)),
            ],
        ),
    ]
