# Generated by Django 4.2.3 on 2023-07-26 03:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GdsSystem', '0004_aoredor_conteudoaplicado_gostam_jogadores'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aoredor',
            old_name='nome',
            new_name='descricao',
        ),
        migrations.RenameField(
            model_name='gostam',
            old_name='nome',
            new_name='descricao',
        ),
    ]
