# Generated by Django 4.2.3 on 2023-08-01 02:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GdsSystem', '0007_disciplina_serie'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Serie',
            new_name='Disciplinas',
        ),
        migrations.RenameModel(
            old_name='Disciplina',
            new_name='Series',
        ),
    ]
